// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvppxwwnuyvohsmkdniq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cHB4d3dudXl2b2hzbWtkbmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjY5MDUsImV4cCI6MjA3NDQwMjkwNX0.HPc5VMwXQJxd7rrDWtpOEAkmEQpaa-0PEtYbxwPytHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});